name: bloc_bootcamp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: packages/shared
  counter:
    path: packages/counter
  timer:
    path: packages/timer
  infinite_list:
    path: packages/infinite_list
  login:
    path: packages/login
  weather:
    path: packages/weather

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  melos: ^3.1.1

flutter:
  uses-material-design: true
