name: infinite_list
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.2
  http: ^1.1.0
  stream_transform: ^2.1.0

  shared:
    path: ../shared

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
