name: login
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.6.0
  shared:
    path: ../shared
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
